language: node_js
node_js:
  - "node"

cache:
  directories:
    - sysconfcpus

install:
  # Required, see https://github.com/elm-lang/elm-compiler/issues/1473#issuecomment-245704142
  - |
      if [ ! -d sysconfcpus/bin ];
      then
        git clone https://github.com/obmarg/libsysconfcpus.git;
        cd libsysconfcpus;
        ./configure --prefix=$TRAVIS_BUILD_DIR/sysconfcpus;
        make && make install;
        cd ..;
      fi
  - "npm install -g elm yarn"
  - "yarn"
  - "elm package install -y"
    
script:
  - "$TRAVIS_BUILD_DIR/sysconfcpus/bin/sysconfcpus -n 1 ./node_modules/webpack/bin/webpack.js"
